// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: rag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\x03rag\"*\n" +
	"\fQueryRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"%\n" +
	"\rQueryResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token27\n" +
	"\x03RAG\x120\n" +
	"\x05Query\x12\x11.rag.QueryRequest\x1a\x12.rag.QueryResponse0\x01B\x13Z\x11fininsights/pb;pbb\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rag_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: rag.QueryRequest
	(*QueryResponse)(nil), // 1: rag.QueryResponse
}
var file_rag_proto_depIdxs = []int32{
	0, // 0: rag.RAG.Query:input_type -> rag.QueryRequest
	1, // 1: rag.RAG.Query:output_type -> rag.QueryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
