// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: rag.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RAG_Query_FullMethodName = "/rag.RAG/Query"
)

// RAGClient is the client API for RAG service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RAGClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
}

type rAGClient struct {
	cc grpc.ClientConnInterface
}

func NewRAGClient(cc grpc.ClientConnInterface) RAGClient {
	return &rAGClient{cc}
}

func (c *rAGClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RAG_ServiceDesc.Streams[0], RAG_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RAG_QueryClient = grpc.ServerStreamingClient[QueryResponse]

// RAGServer is the server API for RAG service.
// All implementations must embed UnimplementedRAGServer
// for forward compatibility.
type RAGServer interface {
	Query(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error
	mustEmbedUnimplementedRAGServer()
}

// UnimplementedRAGServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAGServer struct{}

func (UnimplementedRAGServer) Query(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedRAGServer) mustEmbedUnimplementedRAGServer() {}
func (UnimplementedRAGServer) testEmbeddedByValue()             {}

// UnsafeRAGServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAGServer will
// result in compilation errors.
type UnsafeRAGServer interface {
	mustEmbedUnimplementedRAGServer()
}

func RegisterRAGServer(s grpc.ServiceRegistrar, srv RAGServer) {
	// If the following call panics, it indicates UnimplementedRAGServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RAG_ServiceDesc, srv)
}

func _RAG_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RAGServer).Query(m, &grpc.GenericServerStream[QueryRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RAG_QueryServer = grpc.ServerStreamingServer[QueryResponse]

// RAG_ServiceDesc is the grpc.ServiceDesc for RAG service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAG_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.RAG",
	HandlerType: (*RAGServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _RAG_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rag.proto",
}
